### ISSUE TITLE
QuickDocsPHP

### ISSUE THREAD

**Issue by Wikunia** [DannyMoerkerke/brackets-php-doc#1]
Hi Danny,

maybe you want to check out my https://github.com/Wikunia/brackets-QuickDocsPHP extension which provides the PHPDocs from `php.net` in the editor itself.

**Comment by DannyMoerkerke** [comment]
Hi Ole,

Yes I already installed that one (did not know it was yours) as well as
your quick docs extensions for Javascript and regex but unfortunately for
PHP it's not working in my editor.
I attached a screenshot of the notice I get.



2015-01-18 11:06 GMT+01:00 Ole Kröger <notifications@github.com>:

**Comment by Wikunia** [comment]
Hi Danny,

can you open an issue and attach the image? Looks like attaching doesn't work via mail.

**Comment by DannyMoerkerke** [comment]
I now notice that it does work for "file_get_contents" for example but not
for "try" or "return" but I guess that is the way it's supposed to work (?)


2015-01-18 21:14 GMT+01:00 Ole Kröger <notifications@github.com>:

**Comment by Wikunia** [comment]
Yes I don't support every function so if you miss sth you can add an issue :)
Have a nice day!

**Comment by DannyMoerkerke** [comment]
Ok I see it works for user defined functions as well, that's very
interesting!
Will study your code ;-)

Cheers!


2015-01-18 21:23 GMT+01:00 Ole Kröger <notifications@github.com>:
